name: Build and Test Hello World App
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t devopsimage .

      - name: Create custom network
        run: docker network create se-methods || true

      - name: Run container with custom network
        run: |
          docker run --name devopscontainer --network se-methods -d devopsimage
          sleep 15  # Wait for app to start

      - name: View logs
        run: docker logs devopscontainer

      - name: Check network connectivity
        run: |
          docker network ls
          docker inspect devopscontainer | grep -A 10 "NetworkSettings"

      - name: Cleanup
        if: always()
        run: |
          docker stop devopscontainer || true
          docker rm devopscontainer || true
          docker network rm se-methods || true