name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile with Maven
        run: mvn compile
      - name: Build Docker Image
        run: docker build -t seMethodsimage .
      - name: Run image
        run: docker run --name seMethodscontainer -d seMethodsimage
      - name: view logs
        run: docker logs seMethodscontainer
